[pytest]
# Automatically load environment variables from the .env file
addopts = --import-mode=importlib --html=reports/report.html --self-contained-html --screenshot=only-on-failure --video=retain-on-failure

# Register custom markers (optional, but good practice)
markers = 
	smoke: quick smoke tests
	regression: full regression suite
